name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-javascript:
    name: JavaScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          LOG_LEVEL: debug
        with:
          configuration_file: example/postgres-to-csv.yaml
          base_folder: insta-integration-test
          data_caterer_user: ${{ secrets.DATA_CATERER_USER }}
          data_caterer_token: ${{ secrets.DATA_CATERER_TOKEN }}

      - name: Print Output
        id: output
        run: |
          echo "Records generated:         ${{ steps.test-action.outputs.num_records_generated }}"
          echo "Successful validations:    ${{ steps.test-action.outputs.num_success_validations }}"
          echo "Failed validations:        ${{ steps.test-action.outputs.num_failed_validations }}"
          echo "Number of validations:     ${{ steps.test-action.outputs.num_validations }}"
          echo "Validation success rate:   ${{ steps.test-action.outputs.validation_success_rate }}"
